name: Python Rename

on:
  push:
    branches:
      - main

jobs:
  rename_hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Rename Python script
      run: mv hello.py new_hello.py

    - name: Run Python script
      run: python new_hello.py

